services:
  local-s3:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z.fips
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
    - MINIO_ROOT_USER=anbiasenggagau
    - MINIO_ROOT_PASSWORD=supersecret
    - MINIO_VOLUMES=/data
    volumes:
      - ./data:/data/
    command: minio server /data --console-address ":9001"

# to start minio server, run this command
# minio server /data

# there will be console address which can be used to manage objects via web-based GUI
# to specify which console address should be open at, use flag --console-address
# otherwise, minio will randomly select available port