services:
  local-s3:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z.fips
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
    - MINIO_ROOT_USER=anbiasenggagau
    - MINIO_ROOT_PASSWORD=supersecret
    - MINIO_VOLUMES=/data
    volumes:
      - ./data:/data/
    command: minio server /data --console-address ":9001"